imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi: ~
    translator: { fallback: %locale% }
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
    assets:
        # basic css compilation
        compiled_css:
            output: css/compiled.css
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
                - %kernel.root_dir%/../vendor/bmatzner/fontawesome-bundle/Bmatzner/FontAwesomeBundle/Resources/public/css/font-awesome.css
            filters:
                - cssrewrite
        # responsive css compilation
        responsive_css:
            output: css/responsive.css
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/responsive-utilities.less
            filters:
                - cssrewrite
        # all js compilation
        compiled_js:
            output: js/compiled.js
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js

# Propel configuration
propel:
    build_properties:
        propel.useDateTimeClass: true
        propel.dateTimeClass: DateTime
        propel.defaultTimeStampFormat: null
        propel.defaultTimeFormat: null
        propel.defaultDateFormat: null
        propel.mysql.tableType: InnoDB

        propel.builder.pluralizer.class: builder.util.StandardEnglishPluralizer

    # db connections
    dbal:
        default_connection:           default
        connections:
            default:
                driver:               %database_driver%
                user:                 %database_user%
                password:             %database_password%
                dsn:                  %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
                options:              {}
                attributes:           {}

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Knp menu
knp_menu:
    twig:
        template: MopaBootstrapBundle:Menu:menu.html.twig
